### ISSUE TITLE
Error: LIBUSB_ERROR_ACCESS

### ISSUE THREAD

**Issue by RogierQ** [smadds/node-red-contrib-udmx#2]
After installing all usb extra's i still get an error like below:
Error: LIBUSB_ERROR_ACCESS
It is running on a raspberry pi and i cannot find a solution to solve it :-(

Do you have any idea what the problem should be?

**Comment by smadds** [comment]
Seems to be a problem compiling [node-usb](https://github.com/tessel/node-usb/) at the moment. It's failing to get the required source code.

**Comment by livewild1988** [comment]
thank for your reply
so what should i do

**Comment by smadds** [comment]
I have found compilation errors on an ARM processor, which was missing a library. 
Try installing this first:
`sudo apt install libudev-dev`

**Comment by smadds** [comment]
Just had an issue getting UDMX installed on RPi - turned out to be the distro lacking pkg-config. This sorted it:
`sudo apt install pkg-config`
